vars: {
    d2-config: {
      layout-engine: elk
      # Terminal theme code
      theme-id: 300
    }
  }
  network: {
    cell tower: {
        shape: stored_data
        style.multiple: true
      }
  
      transmitter
  
    }
  
    online portal: {
      ui: {shape: hexagon}
    }
  
    data processor: {
      storage: {
        shape: cylinder
        style.multiple: true
      }
    }
  
    cell tower.transmitter -> data processor.storage: phone logs

  user: {
    shape: person
    width: 130
  }
  
  user -> network.cell tower: make call
  user -> network.online portal.ui: access {
    style.stroke-dash: 3
  }
  
  api server -> network.online portal.ui: display
  api server -> logs: persist
  logs: {shape: page; style.multiple: true}
  
  network.data processor -> api server

CryptHub Platform: "" {
    explanation: |md
    # `CryptHub` **Platform**
    ## An `Integrated Hacking Environment`
    - Features, Integrations, and Applications
    |

}

feature: Feature {
    style.multiple: true
    shape: step
}

feature-list: {
    feature -> CryptDB Features
    feature -> CryptBucket Feature
}

CryptHub Features: "Feature" {
    explanation: |md
    # `CryptHub` **Features**
    |
    feature-list: {
        feature -> CryptDB Features
        feature -> CryptBucket Feature
    }
}

CryptDB Feature: "Feature" {
    explanation: |md
    # `CryptDB` **Feature**
    ## `CryptDB` serves as the **primary database** for the `CryptHub` platform.
    |

}


CryptBucket Feature: "Feature" {
    explanation: |md
    # `CryptDB` **Feature**
    ## `CryptDB` serves as the **primary database** for the `CryptHub` platform.
    |
}
